server:
  port: 8090
spring:
  application:
    name: api-gateway
  kafka:
    bootstrap-servers: 120.78.168.132:9092
logging:
  config: classpath:log4j2_dev.xml
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
env:
  test29
